INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        1,
        'KMK4579815179',
        'House For Sale',
        'House For Sale',
        200000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/vUoKMuPRyAosbgA1ZclX3EOuSFYxOtdd092UZmPY.jpg","uploads\\/property_images\\/br9deoSNOOeT9kXOBhdRT2yZla0g4BjCyYlj6XPm.jpg","uploads\\/property_images\\/9s8VPvojl0LfpPObb1qmHmyVp5dZL2NzGjTxto4R.jpg","uploads\\/property_images\\/so7w569LHftYDVIQxrdNBdXVcZUgEbV3myxkvUfs.jpg","uploads\\/property_images\\/79X1BAYlBZ5XufGDHBJ040zDWEHbRt94ZKNyojih.jpg"]',
        'Bhilai',
        2,
        1,
        'Semi Furnished',
        'On Progress',
        'Owner',
        'North',
        'JK Builders',
        23,
        21,
        555,
        1,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        'house-for-sale',
        NULL,
        '1',
        '2024-09-18 18:38:23',
        '2024-09-18 18:38:23'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        2,
        'KMK1758103742',
        'Real kmk bank property',
        'बैंक साइजिंग प्रॉपर्टी में करते जल्द से जल्द',
        2000000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/hzvxPLM3IWYeZumUU5K1QYlM81EiMq9JGREtNxlm.jpg"]',
        'Delhi',
        3,
        2,
        'Not',
        'Delhi',
        'Bank',
        'Weat',
        'Realkmk',
        1200,
        1400,
        2000,
        2,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        'real-kmk-bank-property',
        NULL,
        '1',
        '2024-09-19 04:45:39',
        '2024-09-19 04:45:39'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        3,
        'KMK2421763847',
        '1 बीएचके फ्लैट इन कोलकाता लेक टाउन',
        '1 बीएचके फ्लैट इन कोलकाता लेक टाउन',
        1480000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/T5LIfPgzGZmEmWOtlXz7jkIIG5sMrrvhvzwcoBJz.jpg","uploads\\/property_images\\/U08Feoid5fnnBWF8RP9vyek4krYWfwbv7ToNFznx.jpg","uploads\\/property_images\\/glUBDT9t8FxXsn0y6gbDQrnZULYLQVFJ2eG4SQE1.jpg","uploads\\/property_images\\/bXkhyZRt7y6zTUYla8nktHJtQunBt807JU7QflTF.jpg"]',
        'Kolkata',
        1,
        1,
        'Not',
        'Sale',
        'Owner',
        'West',
        'Realkmk',
        400,
        450,
        2000,
        3,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        '1-becaka-falta-ina-kalkata-lka-tauna',
        NULL,
        '1',
        '2024-09-20 02:37:54',
        '2024-09-20 02:37:54'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        4,
        'KMK3716122758',
        '2 BHK flat for sale in Kolkata best flat',
        '6290545905 \r\n2 BHK flat for sale in Kolkata best flat second floor this is owner number contact us',
        1900000.00,
        1,
        1,
        11,
        NULL,
        'Kolkata',
        2,
        1,
        'Not',
        'Ready to move',
        'Owner',
        'East',
        'Real kmk',
        450,
        450,
        500,
        4,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        '2-bhk-flat-for-sale-in-kolkata-best-flat',
        NULL,
        '1',
        '2024-09-20 02:49:22',
        '2024-09-20 02:49:22'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        5,
        'KMK1174590567',
        '2 BHK flat for sale in Kolkata best flat',
        '6290545905\r\n2 BHK flat for sale in Kolkata best flat',
        1890000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/sqNbponXmGlBJvW0MOSKGWF4lHb12eEQQzRuB20T.jpg","uploads\\/property_images\\/woV1oBjAFgEHSwgjtRrCAdIghxb5wMXVAH93mXjO.jpg","uploads\\/property_images\\/5sb2VCAcrCCTWrsPVkE0FKSklqlJ5hYzn1s7xPpK.jpg","uploads\\/property_images\\/K4s59pHOtDbU97wO6pEr2hk0ka8zpapMjkpr6pOg.jpg"]',
        'Kolkata',
        2,
        1,
        'Not',
        'Ready to move',
        'Realkmk',
        'East',
        'Real kmk',
        450,
        500,
        500,
        4,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        '2-bhk-flat-for-sale-in-kolkata-best-flat',
        NULL,
        '1',
        '2024-09-20 02:57:36',
        '2024-09-20 02:57:36'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        6,
        'KMK7871731333',
        '79798 73313 flat for sale in Kolkata 3 BHK hurry up contact us',
        'Hurry up 3 BHK flat for sale',
        3490000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/E24NAplPC94kDe5M95e2FUd3mJKCl8iotOUcek5s.jpg"]',
        'Kolkata',
        3,
        2,
        'Not',
        'Ready to move',
        'Real kmk',
        'West',
        'Realkmk',
        500,
        600,
        1000,
        3,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        '79798-73313-flat-for-sale-in-kolkata-3-bhk-hurry-up-contact-us',
        NULL,
        '1',
        '2024-09-20 03:05:02',
        '2024-09-20 03:05:02'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        7,
        'KMK2854380734',
        'realkmk.com बैंक साइजिंग प्रॉपर्टी एंड ऑनर प्रॉपर्टी',
        'बैंक साइजिंग प्रॉपर्टी और ऑनर की प्रॉपर्टी हमारे यहां उपलब्ध है जल्द करें और अपने प्रॉपर्टी खरीदे l',
        4800000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/wLabXuiGhavhLFPwK6Mtzw6GpkZijJiSH4MpOIhZ.jpg"]',
        'Delhi',
        4,
        3,
        'Unfurnished',
        'Ready to move',
        'Realkmk',
        'West',
        'Real kmk',
        1000,
        1200,
        1000,
        3,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        'realkmkcom-bka-saijaga-paraparata-eda-oinara-paraparata',
        NULL,
        '1',
        '2024-09-20 14:12:27',
        '2024-09-20 14:12:27'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        8,
        'KMK7025785725',
        'बैंक साइजिंग प्रॉपर्टी अभी घर बना रहा है',
        'बैंक साइजिंग प्रॉपर्टी और ऑनर की प्रॉपर्टी हमारे यहां उपलब्ध है जल्द करें और अपने प्रॉपर्टी खरीदे l',
        3400000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/wjqqf2mzioE6wnlWPE2jArHb3lSgFiORSOA39ACJ.jpg"]',
        'Delhi',
        4,
        3,
        'Unfurnished',
        'Ready to move',
        'Realkmk',
        'West',
        'Real kmk',
        1000,
        1200,
        2000,
        2,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        'bka-saijaga-paraparata-abha-ghara-bna-raha-ha',
        NULL,
        '1',
        '2024-09-20 14:15:13',
        '2024-09-20 14:15:13'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        9,
        'KMK2378796112',
        'Best house 3 BHK ready to move hurry up',
        'बैंक साइजिंग प्रॉपर्टी और ऑनर की प्रॉपर्टी हमारे यहां उपलब्ध है जल्द करें और अपने प्रॉपर्टी खरीदे l',
        2200000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/AGGRX091YJQmnOhlDH8GTjtDZUpZ3ZWsTaJ9vNna.jpg"]',
        'Delhi',
        3,
        2,
        'Unfurnished',
        'Ready to move',
        'Realkmk',
        'East',
        'Real kmk',
        800,
        1000,
        1500,
        2,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        'best-house-3-bhk-ready-to-move-hurry-up',
        NULL,
        '1',
        '2024-09-20 14:18:02',
        '2024-09-20 14:18:02'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        10,
        'KMK4115041616',
        'Premium property in low price Bank seizing property real kmk.com',
        'बैंक साइजिंग प्रॉपर्टी और ऑनर की प्रॉपर्टी हमारे यहां उपलब्ध है जल्द करें और अपने प्रॉपर्टी खरीदे l',
        200000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/Ct1LliSo7FFxAYdSRHDpsOcQ7LDfCltdxQTMjAJ4.jpg"]',
        'Delhi',
        3,
        2,
        'Unfurnished',
        'Ready to move',
        'Real kmk',
        'East',
        'Realkmk',
        800,
        900,
        1000,
        1,
        NULL,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        'premium-property-in-low-price-bank-seizing-property-real-kmkcom',
        NULL,
        '1',
        '2024-09-20 14:21:54',
        '2024-09-20 14:21:54'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        11,
        'KMK3273756847',
        'Bengaluru Prime location best property',
        'बैंक साइजिंग प्रॉपर्टी और ऑनर की प्रॉपर्टी हमारे यहां उपलब्ध है जल्द करें और अपने प्रॉपर्टी खरीदे l',
        4800000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/IXYjszxOS07AIUZdncdVXWhHP9mXVAsi37SljKJX.jpg"]',
        'Bengaluru',
        4,
        3,
        'Unfurnished',
        'Ready to move',
        'Real kmk',
        'North',
        'Realkmk',
        800,
        1000,
        2000,
        1,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        'bengaluru-prime-location-best-property',
        NULL,
        '1',
        '2024-09-20 14:25:13',
        '2024-09-20 14:25:13'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        12,
        'KMK2243938432',
        '6 BHK Bank seizing property Bangalore best house',
        'बैंक साइजिंग प्रॉपर्टी और ऑनर की प्रॉपर्टी हमारे यहां उपलब्ध है जल्द करें और अपने प्रॉपर्टी खरीदे l',
        9500000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/dt84HFTdrGYR6CniuZSQVPC1Lr3LijpiSAv3G71I.jpg"]',
        'Bengaluru',
        6,
        4,
        'Unfurnished',
        'Ready to move',
        'Owner',
        'South',
        'Realkmk',
        1500,
        1800,
        3000,
        2,
        NULL,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        '6-bhk-bank-seizing-property-bangalore-best-house',
        NULL,
        '1',
        '2024-09-20 14:41:55',
        '2024-09-20 14:41:55'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        13,
        'KMK2813449581',
        '5 BHK premium location in Bangalore buy now',
        'बैंक साइजिंग प्रॉपर्टी और ऑनर की प्रॉपर्टी हमारे यहां उपलब्ध है जल्द करें और अपने प्रॉपर्टी खरीदे l',
        6900000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/bkfKE6oRx8IRzFwPDJJHgnEYlZmR41OcdYDF9f2P.jpg"]',
        'Bengaluru',
        5,
        3,
        'Unfurnished',
        'Ready to move',
        'Owner',
        'North',
        'Real kmk',
        1200,
        1400,
        2000,
        2,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        '5-bhk-premium-location-in-bangalore-buy-now',
        NULL,
        '1',
        '2024-09-20 14:43:46',
        '2024-09-20 14:43:46'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        14,
        'KMK9266572212',
        '3 BHK with car parking Bangalore city',
        'बैंक साइजिंग प्रॉपर्टी और ऑनर की प्रॉपर्टी हमारे यहां उपलब्ध है जल्द करें और अपने प्रॉपर्टी खरीदे l',
        2900000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/gQ6Pt01hO4AxvmlAkDd9OK9Lr2Rcq6XIG3xgydaO.jpg"]',
        'Bengaluru',
        3,
        2,
        'Unfurnished',
        'Ready to move',
        'Owner',
        'West',
        'Real kmk',
        1000,
        1200,
        2000,
        1,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        '3-bhk-with-car-parking-bangalore-city',
        NULL,
        '1',
        '2024-09-20 14:45:17',
        '2024-09-20 14:45:17'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        15,
        'KMK8413103503',
        'Best house in Bengaluru 6 BHK 4 bathroom one hall hurry up',
        'बैंक साइजिंग प्रॉपर्टी और ऑनर की प्रॉपर्टी हमारे यहां उपलब्ध है जल्द करें और अपने प्रॉपर्टी खरीदे l',
        9800000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/0u37Vagdm1zg4ri4XlabiUxNPo0HGEp4aIv0Orwg.jpg"]',
        'Bengaluru',
        6,
        4,
        'Unfurnished',
        'Ready to move',
        'Owner',
        'West',
        'Real kmk',
        1500,
        1800,
        3000,
        3,
        NULL,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        'best-house-in-bengaluru-6-bhk-4-bathroom-one-hall-hurry-up',
        NULL,
        '1',
        '2024-09-20 14:47:34',
        '2024-09-20 14:47:34'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        16,
        'KMK9607231581',
        'Bengaluru 3 BHK sale hurry up',
        'बैंक साइजिंग प्रॉपर्टी और ऑनर की प्रॉपर्टी हमारे यहां उपलब्ध है जल्द करें और अपने प्रॉपर्टी खरीदे l',
        2500000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/uIN2C8hv1Y1OQmnuMUmwlH2zkf6xV4zhknvLMKgC.jpg"]',
        'Bengaluru',
        3,
        2,
        'Unfurnished',
        'Ready to move',
        'Owner',
        'West',
        'Realkmk',
        900,
        1000,
        2000,
        2,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        'bengaluru-3-bhk-sale-hurry-up',
        NULL,
        '1',
        '2024-09-20 14:50:27',
        '2024-09-20 14:50:27'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        17,
        'KMK3168368582',
        'Best house in Mumbai hurry up Bank season property',
        'बैंक साइजिंग प्रॉपर्टी और ऑनर की प्रॉपर्टी हमारे यहां उपलब्ध है जल्द करें और अपने प्रॉपर्टी खरीदे l',
        8500000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/AuUR2OEvswcFzqWKfNspkNj6vN25h0Jfwj7xNRjg.jpg"]',
        'Mumbai',
        5,
        3,
        'Unfurnished',
        'Ready to move',
        'Owner',
        'West',
        'Real kmk',
        1200,
        1400,
        3000,
        2,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        'best-house-in-mumbai-hurry-up-bank-season-property',
        NULL,
        '1',
        '2024-09-20 15:04:26',
        '2024-09-20 15:04:26'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        18,
        'KMK6473609116',
        'Under construction in Mumbai buy now',
        'बैंक साइजिंग प्रॉपर्टी और ऑनर की प्रॉपर्टी हमारे यहां उपलब्ध है जल्द करें और अपने प्रॉपर्टी खरीदे l',
        6900000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/l9NRX4G0mOugi8nMaQPwMwoxjAQNpGP531fmW2ki.jpg"]',
        'Mumbai',
        6,
        4,
        'Unfurnished',
        'Ready to move',
        'Owner',
        'North',
        'Realkmk',
        1400,
        1500,
        4000,
        2,
        NULL,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        'under-construction-in-mumbai-buy-now',
        NULL,
        '1',
        '2024-09-20 15:05:58',
        '2024-09-20 15:05:58'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        19,
        'KMK6623675442',
        'Mumbai ready to move hurry up premium property low price',
        'बैंक साइजिंग प्रॉपर्टी और ऑनर की प्रॉपर्टी हमारे यहां उपलब्ध है जल्द करें और अपने प्रॉपर्टी खरीदे l',
        3800000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/8KkGe6yHtvx95vtQOpJKS4FEDPUyT112TQ7n6WoP.jpg"]',
        'Mumbai',
        4,
        3,
        'Unfurnished',
        'Ready to move',
        'Owner',
        'East',
        'Real kmk',
        1000,
        1200,
        2000,
        2,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        'mumbai-ready-to-move-hurry-up-premium-property-low-price',
        NULL,
        '1',
        '2024-09-20 15:07:51',
        '2024-09-20 15:07:51'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        20,
        'KMK2180286293',
        'Mumbai premium property owner property',
        'बैंक साइजिंग प्रॉपर्टी और ऑनर की प्रॉपर्टी हमारे यहां उपलब्ध है जल्द करें और अपने प्रॉपर्टी खरीदे l',
        2800000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/wQGC46NnWAnLS2MnMLepCr0UvkBhGTmXDpPyZV4G.jpg"]',
        'Mumbai',
        3,
        2,
        'Unfurnished',
        'Ready to move',
        'Realkmk',
        'West',
        'Realkmk',
        1000,
        1100,
        2000,
        2,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        'mumbai-premium-property-owner-property',
        NULL,
        '1',
        '2024-09-20 15:09:29',
        '2024-09-20 15:09:29'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        21,
        'KMK2216278698',
        '6 BHK 4 bathroom one hall two kitchen hurry up Mumbai',
        'बैंक साइजिंग प्रॉपर्टी और ऑनर की प्रॉपर्टी हमारे यहां उपलब्ध है जल्द करें और अपने प्रॉपर्टी खरीदे l',
        6500000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/ACogDveCY2ljSs6oLN4BixA08poXkaeWRpEr8Koh.jpg"]',
        'Mumbai',
        6,
        4,
        'Unfurnished',
        'Ready to move',
        'Realkmk',
        'East',
        'Real kmk',
        1000,
        1300,
        2000,
        2,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        '6-bhk-4-bathroom-one-hall-two-kitchen-hurry-up-mumbai',
        NULL,
        '1',
        '2024-09-20 15:11:10',
        '2024-09-20 15:11:10'
    );
INSERT INTO `listings` (
        `id`,
        `listing_uid`,
        `ad_title`,
        `description`,
        `price`,
        `category_type_id`,
        `category_id`,
        `user_id`,
        `photos`,
        `location`,
        `bedrooms`,
        `bathrooms`,
        `furnishing`,
        `construction_status`,
        `listed_by`,
        `facing`,
        `project_name`,
        `super_builtup_area`,
        `carpet_area`,
        `maintainance`,
        `total_floors`,
        `floor_no`,
        `car_parking`,
        `salary_period`,
        `salary`,
        `position_type`,
        `salary_min_range`,
        `salary_max_range`,
        `premium`,
        `views`,
        `likes`,
        `slug`,
        `expires_at`,
        `status`,
        `created_at`,
        `updated_at`
    )
VALUES (
        22,
        'KMK3184208528',
        '8 BHK 6 bathroom 1 all hurry up to buy now',
        'बैंक साइजिंग प्रॉपर्टी और ऑनर की प्रॉपर्टी हमारे यहां उपलब्ध है जल्द करें और अपने प्रॉपर्टी खरीदे l',
        12000000.00,
        1,
        1,
        11,
        '["uploads\\/property_images\\/IqAmDexBfe5jUMTyDnXhRCgxVfZQh3WtYkOLf4WR.jpg"]',
        'Mumbai',
        8,
        6,
        'Unfurnished',
        'Ready to move',
        'Owner',
        'West',
        'Real kmk',
        1500,
        1800,
        4000,
        2,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        0,
        '8-bhk-6-bathroom-1-all-hurry-up-to-buy-now',
        NULL,
        '1',
        '2024-09-20 15:13:44',
        '2024-09-20 15:13:44'
    );