INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (1, 'Andaman and Nicobar Islands', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (2, 'Andhra Pradesh', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (3, 'Arunachal Pradesh', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (4, 'Assam', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (5, 'Bihar', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (6, 'Chandigarh', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (7, 'Chhattisgarh', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (8, 'Dadra and Nagar Haveli', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (9, 'Daman and Diu', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (10, 'Delhi', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (11, 'Goa', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (12, 'Gujarat', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (13, 'Haryana', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (14, 'Himachal Pradesh', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (15, 'Jammu and Kashmir', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (16, 'Jharkhand', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (17, 'Karnataka', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (18, 'Kenmore', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (19, 'Kerala', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (20, 'Lakshadweep', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (21, 'Madhya Pradesh', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (22, 'Maharashtra', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (23, 'Manipur', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (24, 'Meghalaya', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (25, 'Mizoram', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (26, 'Nagaland', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (27, 'Narora', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (28, 'Natwar', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (29, 'Odisha', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (30, 'Paschim Medinipur', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (31, 'Pondicherry', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (32, 'Punjab', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (33, 'Rajasthan', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (34, 'Sikkim', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (35, 'Tamil Nadu', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (36, 'Telangana', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (37, 'Tripura', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (38, 'Uttar Pradesh', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (39, 'Uttarakhand', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (40, 'Vaishali', 101);
INSERT INTO `states` (`id`, `name`, `country_id`) VALUES (41, 'West Bengal', 101);


INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5312, '24 Parganas (n)', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5313, '24 Parganas (s)', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (316, 'Abhayapuri', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3551, 'Abiramam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3127, 'Abohar', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (779, 'Abrama', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3294, 'Abu Road', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1273, 'Achabal', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2474, 'Achalpur', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4442, 'Achampet', 36);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3552, 'Achampudur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3553, 'Acharapakkam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3554, 'Acharipallam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4531, 'Achhalda', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4532, 'Achhnera', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3555, 'Achipatti', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (780, 'Adalaj', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3128, 'Adampur', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4533, 'Adari', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5, 'Addanki', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3556, 'Adikaratti', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4443, 'Adilabad', 36);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1843, 'Adimaly', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3557, 'Adiramapattinam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (781, 'Adityana', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1518, 'Adityanagar', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1519, 'Adityapatna', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1350, 'Adityapur', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (6, 'Adivivaram', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (7, 'Adoni', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1844, 'Adoor', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5314, 'Adra', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1845, 'Adur', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3558, 'Aduturai', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (782, 'Advana', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3559, 'Adyar', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4534, 'Afzalgarh', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1520, 'Afzalpur', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (8, 'Aganampudi', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2070, 'Agar', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3560, 'Agaram', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4508, 'Agartala', 37);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4535, 'Agarwal Mandi', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3561, 'Agasthiswaram', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2065, 'Agethi', 20);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4536, 'Agra', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4537, 'Agra Cantonment', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2475, 'Aheri', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (595, 'Ahiwara', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2476, 'Ahmadnagar Cantonment', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5315, 'Ahmadpur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2477, 'Ahmadpur', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (783, 'Ahmedabad', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3129, 'Ahmedgarh', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2478, 'Ahmednagar', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4538, 'Ahraura', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (784, 'Ahwa', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5316, 'Aiho', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4539, 'Ailum', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4540, 'Air Force Area', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5317, 'Aistala', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2935, 'Aizawl', 25);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2071, 'Ajaigarh', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4541, 'Ajhuwa', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1521, 'Ajjampur', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (9, 'Ajjaram', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3295, 'Ajmer', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3130, 'Ajnala', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2479, 'Ajra', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3131, 'Akalgarh', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2480, 'Akalkot', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (596, 'Akaltara', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1846, 'Akathiyur', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4542, 'Akbarpur', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1274, 'Akhnur', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (10, 'Akividu', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2481, 'Akkalkuwa', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3562, 'Akkaraipettai', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (11, 'Akkarampalle', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (12, 'Akkayapalle', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (13, 'Akkireddipalem', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3296, 'Aklera', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2072, 'Akoda', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2073, 'Akodia', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2482, 'Akola', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2483, 'Akot', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3563, 'Alagappapuram', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3564, 'Alagapuri', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3565, 'Alampalayam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (14, 'Alampur', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2074, 'Alampur', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1522, 'Aland', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2484, 'Alandi', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3566, 'Alandur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (785, 'Alang', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1847, 'Alangad', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3567, 'Alanganallur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3568, 'Alangayam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3569, 'Alangudi', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3570, 'Alangulam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3571, 'Alanthurai', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3572, 'Alapakkam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1848, 'Alappuzha', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4543, 'Alapur', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3132, 'Alawalpur', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (708, 'Aldona', 11);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2485, 'Alibag', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4544, 'Aliganj', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4545, 'Aligarh', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5318, 'Alipur Duar', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5319, 'Alipur Duar Railway Junction', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2075, 'Alirajpur', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4546, 'Allahabad', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4547, 'Allahabad Cantonment', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4548, 'Allahganj', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2486, 'Allapalli', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3573, 'Allapuram', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1523, 'Almatti Sitimani', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5219, 'Almora', 39);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5220, 'Almora Cantonment', 39);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1524, 'Alnavar', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (299, 'Along', 3);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2487, 'Alore', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2076, 'Alot', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5320, 'Alpur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (709, 'Altinho', 11);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3574, 'Alur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1525, 'Alur', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1849, 'Aluva', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3297, 'Alwar', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3575, 'Alwar Tirunagari', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3576, 'Alwarkurichi', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (15, 'Amalapuram', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5321, 'Amalhara', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2488, 'Amalner', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2077, 'Amanganj', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4549, 'Amanpur', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2078, 'Amarkantak', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2079, 'Amarpatan', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (448, 'Amarpur', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4509, 'Amarpur', 37);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2080, 'Amarwara', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2489, 'Ambad', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2081, 'Ambada', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (597, 'Ambagarh Chauki', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2082, 'Ambah', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4550, 'Ambahta', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (786, 'Ambaji', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2490, 'Ambajogai', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1096, 'Ambala', 13);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1097, 'Ambala Cantt', 13);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (787, 'Ambaliyasan', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3577, 'Ambasamudram', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4510, 'Ambassa', 37);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2491, 'Ambernath', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1526, 'Ambikanagara', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (317, 'Ambikapur', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (598, 'Ambikapur', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2492, 'Ambivali Tarf Wankhal', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3578, 'Ambur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3298, 'Amet', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4551, 'Amethi', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2493, 'Amgaon', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (318, 'Amguri', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4552, 'Amila', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4553, 'Amilo', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4554, 'Aminagar Sarai', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4555, 'Aminagar Urf Bhurbaral', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2066, 'Amini', 20);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5322, 'Amkula', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2083, 'Amla', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1351, 'Amlabad', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5323, 'Amlagora', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2084, 'Amlai', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (702, 'Amli', 8);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3133, 'Amloh', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3579, 'Ammainaickanur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3580, 'Ammaparikuppam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3581, 'Ammapettai', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3582, 'Ammavarikuppam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3583, 'Ammur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (788, 'Amod', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5324, 'Amodghata', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4556, 'Amraudha', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2494, 'Amravati', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (789, 'Amreli', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3134, 'Amritsar', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3135, 'Amritsar Cantonment', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4557, 'Amroha', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (790, 'Amroli', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5325, 'Amtala', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (16, 'Amudalavalasa', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (17, 'Amur', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3584, 'Anaimalai', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3585, 'Anaiyur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (18, 'Anakapalle', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3586, 'Anakaputhur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (791, 'Anand', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (319, 'Anand Nagar', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2966, 'Anandapur', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4558, 'Anandnagar', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3136, 'Anandpur Sahib', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (19, 'Anantapur', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3587, 'Ananthapuram', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1275, 'Anantnag', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1850, 'Ancharakandy', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (792, 'Andada', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3588, 'Andanappettai', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3589, 'Andipalayam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3590, 'Andippatti', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (20, 'Andole', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2884, 'Andro', 23);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2067, 'Androth Island', 20);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5326, 'Andul', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1527, 'Anekal', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1851, 'Angamaly', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1352, 'Angarpathar', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2967, 'Angul', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2085, 'Anjad', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2495, 'Anjangaon', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (793, 'Anjar', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3591, 'Anjugramam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (794, 'Anklav', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (795, 'Ankleshwar', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (796, 'Anklesvar INA', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1528, 'Ankola', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5327, 'Anksa', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5328, 'Ankurhati', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3592, 'Annamalainagar', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3593, 'Annavasal', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1529, 'Annigeri', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3594, 'Annur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4559, 'Anpara', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3299, 'Antah', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (797, 'Antaliya', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3595, 'Anthiyur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2086, 'Antri', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4560, 'Antu', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5329, 'Anup Nagar', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3300, 'Anupgarh', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2087, 'Anuppur', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4561, 'Anupshahr', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4562, 'Aonla', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3596, 'Appakudal', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (710, 'Aquem', 11);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1353, 'Ara', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (449, 'Ara', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3597, 'Arachalur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3598, 'Arakandanallur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3599, 'Arakonam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3600, 'Aralvaimozhi', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5330, 'Arambagh', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (798, 'Arambhada', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (599, 'Arang', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3601, 'Arani', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3602, 'Arani Road', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3603, 'Arantangi', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (450, 'Araria', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3604, 'Arasiramani', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3605, 'Aravakurichi', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3606, 'Aravankadu', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3607, 'Arcot', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (451, 'Areraj', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5331, 'Argari', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3119, 'Ariankuppam', 31);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3608, 'Arimalam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3609, 'Ariyalur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3610, 'Ariyappampalayam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3611, 'Ariyur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1530, 'Arkalgud', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1205, 'Arki', 14);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4563, 'Armapur Estate', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4444, 'Armoor', 36);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3612, 'Arni', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1276, 'Arnia', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2088, 'Aron', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1852, 'Aroor', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (711, 'Arpora', 11);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5332, 'Arsha', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1531, 'Arsikere', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1853, 'Arukutti', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3613, 'Arulmigu Thirumuruganpundi', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3614, 'Arumanai', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3615, 'Arumbavur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3616, 'Arumuganeri', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3617, 'Aruppukkottai', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2496, 'Arvi', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1098, 'Asan Khurd', 13);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1099, 'Asandh', 13);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5333, 'Asansol', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (452, 'Asarganj', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (799, 'Asarma', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3618, 'Ashokapuram', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2089, 'Ashoknagar', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5334, 'Ashoknagar Kalyangarh', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4564, 'Ashokpuram', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4565, 'Ashrafpur Kichhauchha', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2090, 'Ashta', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2497, 'Ashta', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2498, 'Ashti', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4445, 'Asifabad', 36);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3301, 'Asind', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2968, 'Aska', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4566, 'Atarra', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4567, 'Atasu', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1100, 'Ateli', 13);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3619, 'Athani', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3620, 'Athanur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2969, 'Athgarh', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3621, 'Athimarapatti', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3622, 'Athipattu', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2970, 'Athmallik', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1532, 'Athni', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3623, 'Athur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (21, 'Atmakur', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4568, 'Atrauli', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4569, 'Atraulia', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3624, 'Attayyampatti', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (22, 'Attili', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1854, 'Attingal', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3625, 'Attur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (800, 'Atul', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1533, 'Aurad', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4570, 'Auraiya', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4571, 'Aurangabad', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (453, 'Aurangabad', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5335, 'Aurangabad', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2499, 'Aurangabad', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4572, 'Aurangabad Bangar', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2500, 'Aurangabad Cantonment', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4573, 'Auras', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3626, 'Auroville', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2501, 'Ausa', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3627, 'Avadattur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3628, 'Avadi', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3629, 'Avalpundurai', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3630, 'Avaniapuram', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (23, 'Avanigadda', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3631, 'Avinashi', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1855, 'Avinissery', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4574, 'Awagarh', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1277, 'Awantipora', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3632, 'Ayakudi', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3633, 'Ayanadaippu', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3634, 'Aygudi', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4575, 'Ayodhya', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3635, 'Ayothiapattinam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3636, 'Ayyalur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3637, 'Ayyampalayam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3638, 'Ayyampettai', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4576, 'Azamgarh', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3639, 'Azhagiapandiapuram', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1856, 'Azhikode North', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1857, 'Azhikode South', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1858, 'Azhiyur', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4577, 'Azizpur', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4578, 'Azmatgarh', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2091, 'Babai', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4579, 'Babarpur Ajitmal', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4580, 'Baberu', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2502, 'Babhulgaon', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4581, 'Babina', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1101, 'Babiyal', 13);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5336, 'Bablari Dewanganj', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (801, 'Babra', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4582, 'Babrala', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1354, 'Babua Kalan', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4583, 'Babugarh', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4584, 'Bachhiowan', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4585, 'Bachhraon', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4586, 'Bad', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2092, 'Bada Malhera', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2093, 'Badagaon', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1534, 'Badagavettu', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2094, 'Badagoan', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1535, 'Badami', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1278, 'Badami Bagh', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (320, 'Badarpur', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (321, 'Badarpur Railway Town', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2095, 'Badarwas', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4587, 'Badaun', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2096, 'Badawada', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1206, 'Baddi', 14);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (600, 'Bade Bacheli', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (24, 'Badepalli', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4446, 'Badepally', 36);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5337, 'Badhagachhi', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4511, 'Badharghat', 37);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3137, 'Badhni Kalan', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2097, 'Badi', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2098, 'Badkuhi', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2503, 'Badlapur', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2099, 'Badnagar', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2100, 'Badnawar', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2101, 'Badod', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2102, 'Badoda', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2103, 'Badra', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5221, 'Badrinathpuri', 39);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5338, 'Baduria', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (25, 'Badvel', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (802, 'Bag-e-Firdosh', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (454, 'Bagaha', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1536, 'Bagalkot', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3302, 'Bagar', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (803, 'Bagasara', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (601, 'Bagbahara', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1355, 'Bagbahra', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1537, 'Bagepalli', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5222, 'Bageshwar', 39);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2104, 'Bagh', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3138, 'Bagh Purana', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5339, 'Baghdogra', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2919, 'Baghmara', 24);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4588, 'Baghpat', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2105, 'Bagli', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5340, 'Bagnan', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5341, 'Bagra', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3303, 'Bagru', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5342, 'Bagula', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4589, 'Bah', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5223, 'Bah Bazar', 39);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (804, 'Bahadarpar', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (455, 'Bahadurganj', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4590, 'Bahadurganj', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1102, 'Bahadurgarh', 13);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5343, 'Baharampur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (322, 'Bahbari Gaon', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4591, 'Baheri', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5344, 'Bahirgram', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4592, 'Bahjoi', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4593, 'Bahraich', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3304, 'Bahror', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4594, 'Bahsuma', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4595, 'Bahua', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5345, 'Bahula', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5346, 'Baidyabati', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2106, 'Baihar', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2107, 'Baikunthpur', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (602, 'Baikunthpur', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1538, 'Bailhongal', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1539, 'Baindur', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2936, 'Bairabi', 25);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5347, 'Bairatisal', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (456, 'Bairgania', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5348, 'Baj Baj', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1540, 'Bajala', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (805, 'Bajipura', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4596, 'Bajna', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1541, 'Bajpe', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (806, 'Bajva', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3305, 'Bakani', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4597, 'Bakewar', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (457, 'Bakhtiyarpur', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4598, 'Bakiabad', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1207, 'Bakloh', 14);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5349, 'Bakreswar', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2108, 'Bakswaha', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3139, 'Balachaur', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2109, 'Balaghat', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2971, 'Balagoda', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3640, 'Balakrishnampatti', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3641, 'Balakrishnapuram', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2972, 'Balangir', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3642, 'Balapallam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (26, 'Balapur', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2504, 'Balapur', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5350, 'Balaram Pota', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5351, 'Balarampur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3643, 'Balasamudram', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (807, 'Balasinor', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2973, 'Balasore', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4599, 'Baldeo', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2110, 'Baldeogarh', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2974, 'Baleshwar', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3306, 'Bali', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5352, 'Bali Chak', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1356, 'Baliapur', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1357, 'Baliari', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2975, 'Balimeta', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1358, 'Balkundra', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1103, 'Ballabgarh', 13);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2505, 'Ballarpur', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5353, 'Ballavpur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4600, 'Ballia', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5354, 'Bally', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (603, 'Balod', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (604, 'Baloda', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (605, 'Baloda Bazar', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3307, 'Balotra', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4601, 'Balrampur', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2976, 'Balugaon', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5355, 'Balurghat', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1859, 'Balussery', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2111, 'Bamaniya', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (712, 'Bambolim', 11);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2112, 'Bamhani', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2113, 'Bamor', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2114, 'Bamora', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (323, 'Bamun Sualkuchi', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5356, 'Bamunari', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2977, 'Banapur', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5357, 'Banarhat Tea Garden', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (606, 'Banarsi', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (808, 'Banaskantha', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4602, 'Banat', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3140, 'Banaur', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1542, 'Banavar', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5224, 'Banbasa', 39);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2115, 'Banda', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4603, 'Banda', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (27, 'Bandarulanka', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5358, 'Bandel', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1359, 'Bandhgora', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5225, 'Bandia', 39);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3308, 'Bandikui', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1279, 'Bandipur', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (713, 'Bandora', 11);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3141, 'Banga', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (28, 'Banganapalle', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5359, 'Bangaon', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1543, 'Bangarapet', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4604, 'Bangarmau', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2116, 'Bangawan', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1860, 'Bangramanjeshwar', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2978, 'Bangura', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1280, 'Banihal', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1208, 'Banjar', 14);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (458, 'Banka', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1544, 'Bankapura', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4605, 'Banki', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2979, 'Banki', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5360, 'Bankra', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5361, 'Bankura', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (459, 'Banmankhi', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1545, 'Bannur', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2980, 'Banposh', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2117, 'Bansatar Kheda', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5362, 'Bansbaria', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (809, 'Bansda', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4606, 'Bansdih', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4607, 'Bansgaon', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5363, 'Banshra', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4608, 'Bansi', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4447, 'Banswada', 36);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3309, 'Banswara', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (810, 'Bantva', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1546, 'Bantwal', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5364, 'Banupur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3142, 'Banur', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (29, 'Bapatla', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (30, 'Bapulapadu', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (460, 'Bar Bigha', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5365, 'Bara Bamonia', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4609, 'Barabanki', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4610, 'Baragaon', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2118, 'Baraily', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1360, 'Barajamda', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5366, 'Barakpur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5367, 'Barakpur Cantonment', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2506, 'Baramati', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1281, 'Baramula', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1282, 'Baramulla', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3310, 'Baran', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5368, 'Baranagar', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5369, 'Barasat', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (461, 'Barauli', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (462, 'Barauni Oil Township', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4611, 'Baraut', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (324, 'Barbari', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2981, 'Barbil', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5370, 'Barddhaman', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (714, 'Bardez', 11);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (811, 'Bardoli', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4612, 'Bareilly', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4613, 'Bareilly Cantonment', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2119, 'Barela', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3143, 'Baretta', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2982, 'Bargarh', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2120, 'Barghat', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2121, 'Bargi', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3644, 'Bargur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (463, 'Barh', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4614, 'Barhalganj', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4615, 'Barhani', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4616, 'Barhapur', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2122, 'Barhi', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1361, 'Barhi', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (464, 'Barhiya', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3311, 'Bari', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1283, 'Bari Brahmana', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3312, 'Bari Sadri', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (465, 'Bariapur', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2123, 'Barigarh', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5371, 'Barijhati', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2983, 'Baripada', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3144, 'Bariwala', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5372, 'Barjora', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1362, 'Barka Kana', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4617, 'Barkhera', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1363, 'Barki Saraiya', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5226, 'Barkot', 39);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3313, 'Barmer', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3145, 'Barnala', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2984, 'Barpali', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (325, 'Barpathar', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (326, 'Barpeta', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (327, 'Barpeta Road', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5373, 'Barrackpore', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4618, 'Barsana', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2507, 'Barshi', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1364, 'Barughutu', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5374, 'Baruihuda', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5375, 'Baruipur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5376, 'Barunda', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (466, 'Baruni', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4619, 'Barva Sagar', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1365, 'Barwadih', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2124, 'Barwaha', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1104, 'Barwala', 13);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (812, 'Barwala', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2125, 'Barwani', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4620, 'Barwar', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (300, 'Basar', 3);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1366, 'Basaria', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1547, 'Basavakalyan', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1548, 'Basavana Bagevadi', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1284, 'Bashohli', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3314, 'Basi', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5377, 'Basirhat', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5378, 'Baska', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2508, 'Basmat', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (607, 'Basna', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3315, 'Basni Belima', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2126, 'Basoda', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3146, 'Bassi Pathana', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4621, 'Basti', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2985, 'Basudebpur', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (328, 'Basugaon', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1367, 'Basukinath', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3316, 'Baswa', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3147, 'Batala', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3148, 'Bathinda', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1285, 'Batote', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2986, 'Baudh', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1105, 'Bawal', 13);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1106, 'Bawani Khera', 13);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (813, 'Bayad', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3317, 'Bayana', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5227, 'Bazpur', 39);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3318, 'Beawar', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (814, 'Bechar', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (815, 'Bedi', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2509, 'Beed', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2127, 'Begamganj', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5379, 'Begampur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3149, 'Begowal', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4622, 'Begumabad Budhana', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3319, 'Begun', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (467, 'Begusarai', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4623, 'Behat', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (468, 'Behea', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3150, 'Behrampur', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4624, 'Behta Hajipur', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4625, 'Bela', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2987, 'Belagachhia', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1549, 'Belagula', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2988, 'Belaguntha', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1550, 'Belakavadiq', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (31, 'Belampalli', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5380, 'Beldanga', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5381, 'Beldubi', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5382, 'Belebathan', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1551, 'Belgaum', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1552, 'Belgaum Cantonment', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5383, 'Beliator', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4448, 'Bellampalli', 36);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1553, 'Bellary', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1554, 'Belluru', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4512, 'Belonia', 37);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2989, 'Belpahar', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (469, 'Belsand', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1555, 'Beltangadi', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4626, 'Belthara', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3645, 'Belur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1556, 'Belur', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1557, 'Belvata', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (608, 'Bemetra', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (715, 'Benaulim', 11);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1558, 'Bengaluru', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4627, 'Beniganj', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2128, 'Beohari', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2129, 'Berasia', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2990, 'Berhampur', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3646, 'Berhatty', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1107, 'Beri', 13);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1368, 'Bermo', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (32, 'Bestavaripeta', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4628, 'Beswan', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (33, 'Betamcherla', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2130, 'Betma', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (716, 'Betora', 11);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (470, 'Bettiah', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2131, 'Betul', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2132, 'Betul Bazar', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4629, 'Bewar', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1861, 'Beypur', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (816, 'Beyt', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3151, 'Bhabat', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (471, 'Bhabua', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (817, 'Bhachau', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4630, 'Bhadarsa', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3320, 'Bhadasar', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1286, 'Bhaderwah', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4631, 'Bhadohi', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3321, 'Bhadra', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4449, 'Bhadrachalam', 36);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2991, 'Bhadrak', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2510, 'Bhadravati', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1559, 'Bhadravati', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5384, 'Bhadreswar', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3152, 'Bhadur', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (472, 'Bhagalpur', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1369, 'Bhagatdih', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2511, 'Bhagur', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4632, 'Bhagwantnagar', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4450, 'Bhainsa', 36);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2133, 'Bhainsdehi', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3322, 'Bhalariya', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1560, 'Bhalki', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2134, 'Bhamodi', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2512, 'Bhandara', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5385, 'Bhandardaha', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2135, 'Bhander', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5386, 'Bhangar Raghunathpur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5387, 'Bhangri Pratham Khanda', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2992, 'Bhanjanagar', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3153, 'Bhankharpur', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5388, 'Bhanowara', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2136, 'Bhanpura', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (609, 'Bhanpuri', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (818, 'Bhanvad', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4633, 'Bharatganj', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3323, 'Bharatpur', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4634, 'Bhargain', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3154, 'Bharoli Kalan', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4635, 'Bharthana', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (819, 'Bharuch', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (820, 'Bharuch INA', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4636, 'Bharuhana', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2137, 'Bharveli', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4637, 'Bharwari', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3324, 'Bhasawar', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (610, 'Bhatapara', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (611, 'Bhatgaon', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1561, 'Bhatkal', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4638, 'Bhatni Bazar', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4639, 'Bhatpar Rani', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5389, 'Bhatpara', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (34, 'Bhattiprolu', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1370, 'Bhaurah', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2138, 'Bhaurasa', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3647, 'Bhavani', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (821, 'Bhavnagar', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2139, 'Bhavra', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4640, 'Bhawan Bahadurnagar', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3325, 'Bhawani Mandi', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3155, 'Bhawanigarh', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2993, 'Bhawanipatna', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3648, 'Bhawanisagar', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3326, 'Bhawri', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (822, 'Bhayavadar', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2140, 'Bhedaghat', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (823, 'Bhestan', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2513, 'Bhigvan', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2141, 'Bhikangaon', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3156, 'Bhikhi', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3157, 'Bhikhiwind', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (612, 'Bhilai', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2142, 'Bhilakhedi', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3327, 'Bhilwara', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5228, 'Bhim Tal', 39);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1562, 'Bhimarayanagudi', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (35, 'Bhimavaram', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (473, 'Bhimnagar', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (36, 'Bhimunipatnam', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2143, 'Bhind', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3328, 'Bhindar', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4641, 'Bhinga', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2514, 'Bhingar', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3329, 'Bhinmal', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3158, 'Bhisiana', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2144, 'Bhitarwar', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3330, 'Bhiwadi', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2515, 'Bhiwandi', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1108, 'Bhiwani', 13);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1563, 'Bhogadi', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3159, 'Bhogpur', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (474, 'Bhojpur', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4642, 'Bhojpur Dharampur', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1371, 'Bhojudih', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4643, 'Bhokarhedi', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2516, 'Bhokhardan', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5390, 'Bholar Dabri', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4644, 'Bhongaon', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4451, 'Bhongir', 36);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2145, 'Bhopal', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2517, 'Bhor', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2518, 'Bhosari', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1209, 'Bhota', 14);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5229, 'Bhowali', 39);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2994, 'Bhuban', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2995, 'Bhubaneswar', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3160, 'Bhuch', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2146, 'Bhuibandh', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (824, 'Bhuj', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3161, 'Bhulath', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4645, 'Bhulepur', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1372, 'Bhuli', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2519, 'Bhum', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1210, 'Bhuntar', 14);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4452, 'Bhupalpally', 36);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2520, 'Bhusawal', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3649, 'Bhuvanagiri', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2147, 'Biaora', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2937, 'Biate', 25);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (717, 'Bicholim', 11);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2521, 'Bid', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1564, 'Bidar', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5391, 'Bidhannagar', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4646, 'Bidhuna', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5392, 'Bidyadharpur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4647, 'Bighapur', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (475, 'Bihar', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (476, 'Bihar Sharif', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (477, 'Bihariganj', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (329, 'Bihpuria', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1565, 'Bijapur', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2148, 'Bijawar', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1287, 'Bijbiara', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2149, 'Bijeypur', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (330, 'Bijni', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4648, 'Bijnor', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3331, 'Bijoliya Kalan', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2885, 'Bijoy Govinda', 23);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4649, 'Bijpur', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2150, 'Bijrauni', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2151, 'Bijuri', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3332, 'Bikaner', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4650, 'Bikapur', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5393, 'Biki Hakola', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3650, 'Bikketti', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (478, 'Bikramganj', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5394, 'Bilandapur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3333, 'Bilara', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4651, 'Bilari', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (331, 'Bilasipara', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1211, 'Bilaspur', 14);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4652, 'Bilaspur', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1109, 'Bilaspur', 13);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (613, 'Bilaspur', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2152, 'Bilaua', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1566, 'Bilgi', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4653, 'Bilgram', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (614, 'Bilha', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4654, 'Bilhaur', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (825, 'Bilimora', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (826, 'Bilkha', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1288, 'Billawar', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (827, 'Billimora', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2522, 'Biloli', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5395, 'Bilpahari', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2153, 'Bilpura', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4655, 'Bilram', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4656, 'Bilrayaganj', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4657, 'Bilsanda', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4658, 'Bilsi', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2154, 'Bina Railway Colony', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2155, 'Bina-Etawa', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4659, 'Bindki', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2996, 'Binika', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5396, 'Bipra Noapara', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (615, 'Birgaon', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5397, 'Birlapur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2997, 'Birmitrapur', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5398, 'Birnagar', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (479, 'Birpur', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2156, 'Birsinghpur', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1567, 'Birur', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2523, 'Birwadi', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1289, 'Birwah', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4660, 'Bisalpur', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4661, 'Bisanda Buzurg', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5399, 'Bisarpara', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4662, 'Bisauli', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2998, 'Bishama Katek', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4663, 'Bisharatganj', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1290, 'Bishna', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5400, 'Bishnupur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2886, 'Bishnupur', 23);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4664, 'Bisokhar', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3334, 'Bissau', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4665, 'Biswan', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (332, 'Biswanath Chariali', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4666, 'Bithur', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (37, 'Bobbili', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2157, 'Boda', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (828, 'Bodakdev', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (829, 'Bodeli', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (480, 'Bodh Gaya', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4453, 'Bodhan', 36);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3651, 'Bodinayakkanur', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (616, 'Bodri', 7);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (333, 'Bohori', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2524, 'Boisar', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (334, 'Bokajan', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1373, 'Bokaro', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (335, 'Bokokhat', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2999, 'Bolangir', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4454, 'Bollaram', 36);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5401, 'Bolpur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1, 'Bombuflat', 1);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (38, 'Bombuflat', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1568, 'Bommanahalli', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1569, 'Bommasandra', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (39, 'Bommuru', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (301, 'Bondila', 3);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (336, 'Bongaigaon', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (337, 'Bongaigaon Petro-chemical Town', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5402, 'Bongaon', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2525, 'Bop Khel', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (830, 'Bopal', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (338, 'Borgolai', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (831, 'Boria', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (832, 'Boriavi', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1374, 'Borio Bazar', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3335, 'Borkhera', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (833, 'Borsad', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (834, 'Botad', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5403, 'Bowali', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1862, 'Brahmakulam', 19);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3652, 'Brahmana Periya Agraharam', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3000, 'Brahmapur', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2526, 'Brahmapuri', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3001, 'Brajrajnagar', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4667, 'Budaun', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1291, 'Budgam', 15);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3162, 'Budha Theh', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2527, 'Budhgaon', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3163, 'Budhlada', 32);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2158, 'Budhni', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3336, 'Budhpura', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (40, 'Bugganipalle', 2);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4668, 'Bugrasi', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3002, 'Buguda', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4669, 'Bulandshahar', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2528, 'Buldana', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2529, 'Buldhana', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3337, 'Bundi', 33);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1375, 'Bundu', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5404, 'Burdwan', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4670, 'Burhana', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2159, 'Burhanpur', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2160, 'Burhar', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1110, 'Buria', 13);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3003, 'Burla', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3653, 'Buthapandi', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3654, 'Buthipuram', 35);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2530, 'Butibori', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (481, 'Buxar', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1570, 'Byadgi', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (3004, 'Byasanagar', 29);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1571, 'Byatarayanapura', 17);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (718, 'Calapor', 11);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (835, 'Cambay', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (719, 'Candolim', 11);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5405, 'Canning', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (720, 'Caranzalem', 11);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (721, 'Carapur', 11);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5406, 'Cart Road', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (339, 'Chabua', 4);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5407, 'Chachanda', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2161, 'Chachaura Binaganj', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1376, 'Chaibasa', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4671, 'Chail', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1377, 'Chaitudih', 16);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5408, 'Chak Bankola', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5409, 'Chak Enayetnagar', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4672, 'Chak Imam Ali', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5410, 'Chak Kashipur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5411, 'Chakalampur', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2531, 'Chakan', 22);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5412, 'Chakbansberia', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5413, 'Chakdaha', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4673, 'Chakeri', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (2162, 'Chakghat', 21);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (482, 'Chakia', 5);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (4674, 'Chakia', 38);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (836, 'Chaklasi', 12);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (5414, 'Chakpara', 41);
INSERT INTO `cities` (`id`, `name`, `state_id`) VALUES (1378, 'Chakradharpur', 16);
